// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOppz_SNdQys5brvkuhu2AZqunucLsaQ',
    appId: '1:994914626825:web:b8cf608e271330aee3b7d8',
    messagingSenderId: '994914626825',
    projectId: 'musically-d0a36',
    authDomain: 'musically-d0a36.firebaseapp.com',
    storageBucket: 'musically-d0a36.firebasestorage.app',
    measurementId: 'G-PHNCY5J7E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq-8PNRQdI4SQigaA4Qac7du8tACQsHAI',
    appId: '1:994914626825:android:1088ae09f40c67e1e3b7d8',
    messagingSenderId: '994914626825',
    projectId: 'musically-d0a36',
    storageBucket: 'musically-d0a36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdX2Uxk2Ee8EUsrdvoyUBOUR3i8UIH5gk',
    appId: '1:994914626825:ios:150f6d54ab844310e3b7d8',
    messagingSenderId: '994914626825',
    projectId: 'musically-d0a36',
    storageBucket: 'musically-d0a36.firebasestorage.app',
    iosBundleId: 'com.example.musically',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdX2Uxk2Ee8EUsrdvoyUBOUR3i8UIH5gk',
    appId: '1:994914626825:ios:150f6d54ab844310e3b7d8',
    messagingSenderId: '994914626825',
    projectId: 'musically-d0a36',
    storageBucket: 'musically-d0a36.firebasestorage.app',
    iosBundleId: 'com.example.musically',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEOppz_SNdQys5brvkuhu2AZqunucLsaQ',
    appId: '1:994914626825:web:091b17ff85a5458be3b7d8',
    messagingSenderId: '994914626825',
    projectId: 'musically-d0a36',
    authDomain: 'musically-d0a36.firebaseapp.com',
    storageBucket: 'musically-d0a36.firebasestorage.app',
    measurementId: 'G-PVP87X4SS6',
  );
}
